/**
 * @author 
 *
 *   /\_/\  _     ___
 *  |>'v'<||"| -/\, ,`>
 *     -=Edelstein=-
 * 
 */
public class makePurchases extends javax.swing.JFrame {

    /**
     * Creates new form makePurchases
     */
    public makePurchases() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        calculateTotals = new javax.swing.JButton();
        numGrass = new javax.swing.JTextField();
        numWater = new javax.swing.JTextField();
        numStone = new javax.swing.JTextField();
        numLapis = new javax.swing.JTextField();
        taxes = new javax.swing.JLabel();
        subtotal = new javax.swing.JLabel();
        grandTotal = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Liberation Mono", 1, 18)); // NOI18N
        jLabel1.setText("The A-bee-maniation");

        jLabel2.setFont(new java.awt.Font("Liberation Mono", 0, 15)); // NOI18N
        jLabel2.setText("Enter number of each comb you would like to purchase.");

        jLabel3.setFont(new java.awt.Font("Liberation Mono", 0, 15)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grassComb.png"))); // NOI18N
        jLabel3.setText("Grass combs ($9.99):");

        jLabel4.setFont(new java.awt.Font("Liberation Mono", 0, 15)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/waterComb.png"))); // NOI18N
        jLabel4.setText("Water combs($14.99):");

        jLabel5.setFont(new java.awt.Font("Liberation Mono", 0, 15)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stoneComb.png"))); // NOI18N
        jLabel5.setText("Stone combs($19.99):");

        jLabel6.setFont(new java.awt.Font("Liberation Mono", 0, 15)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lapisComb.png"))); // NOI18N
        jLabel6.setText("Lapis combs($49.99):");

        jLabel7.setFont(new java.awt.Font("Liberation Mono", 0, 17)); // NOI18N
        jLabel7.setText("Taxes(13%):");

        jLabel8.setFont(new java.awt.Font("Liberation Mono", 0, 17)); // NOI18N
        jLabel8.setText("Subtotal:");

        jLabel9.setFont(new java.awt.Font("Liberation Mono", 0, 17)); // NOI18N
        jLabel9.setText("Grand Total:");

        calculateTotals.setFont(new java.awt.Font("Liberation Mono", 0, 17)); // NOI18N
        calculateTotals.setText("Calculate");
        calculateTotals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateTotalsActionPerformed(evt);
            }
        });

        numGrass.setColumns(3);
        numGrass.setFont(new java.awt.Font("Liberation Mono", 0, 15)); // NOI18N
        numGrass.setText("0");

        numWater.setColumns(3);
        numWater.setFont(new java.awt.Font("Liberation Mono", 0, 15)); // NOI18N
        numWater.setText("0");

        numStone.setColumns(3);
        numStone.setFont(new java.awt.Font("Liberation Mono", 0, 15)); // NOI18N
        numStone.setText("0");

        numLapis.setColumns(3);
        numLapis.setFont(new java.awt.Font("Liberation Mono", 0, 15)); // NOI18N
        numLapis.setText("0");

        taxes.setFont(new java.awt.Font("Liberation Mono", 0, 17)); // NOI18N
        taxes.setText("0.00");

        subtotal.setFont(new java.awt.Font("Liberation Mono", 0, 17)); // NOI18N
        subtotal.setText("0.00");

        grandTotal.setFont(new java.awt.Font("Liberation Mono", 0, 17)); // NOI18N
        grandTotal.setText("0.00");

        jLabel13.setFont(new java.awt.Font("Liberation Mono", 0, 17)); // NOI18N
        jLabel13.setText("$");

        jLabel14.setFont(new java.awt.Font("Liberation Mono", 0, 17)); // NOI18N
        jLabel14.setText("$");

        jLabel15.setFont(new java.awt.Font("Liberation Mono", 0, 17)); // NOI18N
        jLabel15.setText("$");

        jLabel10.setFont(new java.awt.Font("Liberation Mono", 0, 15)); // NOI18N
        jLabel10.setText("Then just click caluclate!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(numGrass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(47, 47, 47))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(4, 4, 4)
                                        .addComponent(numLapis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(numStone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel14))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(calculateTotals)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel7)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel15)))
                                        .addGap(1, 1, 1)))
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subtotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(taxes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel13)
                                .addGap(5, 5, 5)
                                .addComponent(grandTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel10))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(jLabel1)))
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(numGrass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(numWater, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numStone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(numLapis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(calculateTotals)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(taxes)
                            .addComponent(jLabel7)
                            .addComponent(jLabel15))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(subtotal)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(grandTotal)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, jLabel4, jLabel5, jLabel6});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateTotalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateTotalsActionPerformed
        // variables
        int grassCombs;
        int waterCombs;
        int stoneCombs;
        int lapisCombs;
        
        final double TAX_PERCENT = 0.13;
        final double GRASS_COST = 9.99;
        final double WATER_COST = 14.99;
        final double STONE_COST = 19.99;
        final double LAPIS_COST = 49.99;
        
        double taxCalc;
        double subtotalCalc;
        double grandTotalCalc;
        
        
        // setting variables
        grassCombs = Integer.parseInt(numGrass.getText());
        waterCombs = Integer.parseInt(numWater.getText());
        stoneCombs = Integer.parseInt(numStone.getText());
        lapisCombs = Integer.parseInt(numLapis.getText());
        
        // calculating totals
        subtotalCalc = grassCombs*GRASS_COST + waterCombs*WATER_COST + stoneCombs*STONE_COST + lapisCombs*LAPIS_COST;
        subtotalCalc = subtotalCalc*100;
        subtotalCalc = Math.round(subtotalCalc);
        subtotalCalc = subtotalCalc / 100;
        
        taxCalc = subtotalCalc * TAX_PERCENT;
        taxCalc = taxCalc*100;
        taxCalc = Math.round(taxCalc);
        taxCalc = taxCalc / 100;
        
        grandTotalCalc = taxCalc + subtotalCalc;
        grandTotalCalc = grandTotalCalc*100;
        grandTotalCalc = Math.round(grandTotalCalc);
        grandTotalCalc = grandTotalCalc / 100;
        
        // setting results
        subtotal.setText(String.valueOf(subtotalCalc));
        taxes.setText(String.valueOf(taxCalc));
        grandTotal.setText(String.valueOf(grandTotalCalc));

    }//GEN-LAST:event_calculateTotalsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(makePurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(makePurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(makePurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(makePurchases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new makePurchases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculateTotals;
    private javax.swing.JLabel grandTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField numGrass;
    private javax.swing.JTextField numLapis;
    private javax.swing.JTextField numStone;
    private javax.swing.JTextField numWater;
    private javax.swing.JLabel subtotal;
    private javax.swing.JLabel taxes;
    // End of variables declaration//GEN-END:variables
}
